CREATE OR REPLACE FUNCTION FN_COMBOCOUNTRIES()
RETURNS TABLE (COD_COUNTRY VARCHAR, TXT_COUNTRY VARCHAR) AS
$BODY$

    select  cod_country COD_COUNTRY,
			txt_country TXT_COUNTRY
    from    BUNELI_COUNTRY B
	;
	
$BODY$
LANGUAGE SQL STABLE
ROWS 300;