USE seguro;

insert into `buneli_country`(`cod_country`,`txt_country`) values ('AD','ANDORRA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('AE','UNITED ARAB EMIRATES');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('AF','AFGHANISTAN');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('AG','ANTIGUA AND BARBUDA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('AI','ANGUILLA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('AL','ALBANIA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('AM','ARMENIA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('AO','ANGOLA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('AQ','ANTARCTICA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('AR','ARGENTINA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('AS','AMERICAN SAMOA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('AT','AUSTRIA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('AU','AUSTRALIA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('AW','ARUBA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('AX','ALAND ISLANDS');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('AZ','AZERBAIJAN');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('BA','BOSNIA AND HERZEGOVINA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('BB','BARBADOS');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('BD','BANGLADESH');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('BE','BELGIUM');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('BF','BURKINA FASO');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('BG','BULGARIA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('BH','BAHRAIN');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('BI','BURUNDI');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('BJ','BENIN');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('BL','SAINT BARTH');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('BM','BERMUDA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('BN','BRUNEI DARUSSALAM');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('BO','BOLIVIA, PLURINATIONAL STATE OF');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('BQ','BONAIRE, SINT EUSTATIUS AND SABA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('BR','BRAZIL');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('BS','BAHAMAS');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('BT','BHUTAN');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('BV','BOUVET ISLAND');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('BW','BOTSWANA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('BY','BELARUS');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('BZ','BELIZE');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('CA','CANADA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('CC','COCOS (KEELING) ISLANDS');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('CD','CONGO, THE DEMOCRATIC REPUBLIC OF THE');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('CF','CENTRAL AFRICAN REPUBLIC');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('CG','CONGO');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('CH','SWITZERLAND');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('CI','COTE D''IVOIRE');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('CK','COOK ISLANDS');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('CL','CHILE');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('CM','CAMEROON');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('CN','CHINA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('CO','COLOMBIA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('CR','COSTA RICA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('CU','CUBA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('CV','CAPE VERDE');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('CW','CURA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('CX','CHRISTMAS ISLAND');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('CY','CYPRUS');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('CZ','CZECH REPUBLIC');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('DE','GERMANY');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('DJ','DJIBOUTI');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('DK','DENMARK');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('DM','DOMINICA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('DO','DOMINICAN REPUBLIC');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('DZ','ALGERIA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('EC','ECUADOR');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('EE','ESTONIA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('EG','EGYPT');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('EH','WESTERN SAHARA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('ER','ERITREA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('ES','SPAIN');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('ET','ETHIOPIA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('FI','FINLAND');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('FJ','FIJI');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('FK','FALKLAND ISLANDS (MALVINAS)');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('FM','MICRONESIA, FEDERATED STATES OF');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('FO','FAROE ISLANDS');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('FR','FRANCE');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('GA','GABON');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('GB','UNITED KINGDOM');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('GD','GRENADA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('GE','GEORGIA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('GF','FRENCH GUIANA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('GG','GUERNSEY');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('GH','GHANA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('GI','GIBRALTAR');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('GL','GREENLAND');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('GM','GAMBIA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('GN','GUINEA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('GP','GUADELOUPE');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('GQ','EQUATORIAL GUINEA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('GR','GREECE');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('GS','SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('GT','GUATEMALA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('GU','GUAM');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('GW','GUINEA-BISSAU');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('GY','GUYANA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('HK','HONG KONG');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('HM','HEARD ISLAND AND MCDONALD ISLANDS');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('HN','HONDURAS');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('HR','CROATIA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('HT','HAITI');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('HU','HUNGARY');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('ID','INDONESIA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('IE','IRELAND');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('IL','ISRAEL');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('IM','ISLE OF MAN');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('IN','INDIA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('IO','BRITISH INDIAN OCEAN TERRITORY');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('IQ','IRAQ');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('IR','IRAN, ISLAMIC REPUBLIC OF');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('IS','ICELAND');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('IT','ITALY');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('JE','JERSEY');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('JM','JAMAICA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('JO','JORDAN');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('JP','JAPAN');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('KE','KENYA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('KG','KYRGYZSTAN');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('KH','CAMBODIA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('KI','KIRIBATI');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('KM','COMOROS');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('KN','SAINT KITTS AND NEVIS');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('KP','KOREA, DEMOCRATIC PEOPLE''S REPUBLIC OF');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('KR','KOREA, REPUBLIC OF');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('KW','KUWAIT');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('KY','CAYMAN ISLANDS');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('KZ','KAZAKHSTAN');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('LA','LAO PEOPLE''S DEMOCRATIC REPUBLIC');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('LB','LEBANON');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('LC','SAINT LUCIA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('LI','LIECHTENSTEIN');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('LK','SRI LANKA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('LR','LIBERIA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('LS','LESOTHO');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('LT','LITHUANIA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('LU','LUXEMBOURG');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('LV','LATVIA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('LY','LIBYA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('MA','MOROCCO');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('MC','MONACO');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('MD','MOLDOVA, REPUBLIC OF');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('ME','MONTENEGRO');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('MF','SAINT MARTIN (FRENCH PART)');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('MG','MADAGASCAR');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('MH','MARSHALL ISLANDS');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('MK','MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('ML','MALI');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('MM','MYANMAR');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('MN','MONGOLIA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('MO','MACAO');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('MP','NORTHERN MARIANA ISLANDS');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('MQ','MARTINIQUE');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('MR','MAURITANIA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('MS','MONTSERRAT');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('MT','MALTA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('MU','MAURITIUS');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('MV','MALDIVES');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('MW','MALAWI');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('MX','MEXICO');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('MY','MALAYSIA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('MZ','MOZAMBIQUE');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('NA','NAMIBIA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('NC','NEW CALEDONIA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('NE','NIGER');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('NF','NORFOLK ISLAND');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('NG','NIGERIA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('NI','NICARAGUA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('NL','NETHERLANDS');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('NO','NORWAY');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('NP','NEPAL');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('NR','NAURU');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('NU','NIUE');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('NZ','NEW ZEALAND');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('OM','OMAN');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('PA','PANAMA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('PE','PERU');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('PF','FRENCH POLYNESIA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('PG','PAPUA NEW GUINEA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('PH','PHILIPPINES');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('PK','PAKISTAN');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('PL','POLAND');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('PM','SAINT PIERRE AND MIQUELON');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('PN','PITCAIRN');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('PR','PUERTO RICO');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('PS','PALESTINIAN TERRITORY, OCCUPIED');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('PT','PORTUGAL');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('PW','PALAU');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('PY','PARAGUAY');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('QA','QATAR');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('RE','REUNION');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('RO','ROMANIA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('RS','SERBIA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('RU','RUSSIAN FEDERATION');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('RW','RWANDA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('SA','SAUDI ARABIA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('SB','SOLOMON ISLANDS');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('SC','SEYCHELLES');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('SD','SUDAN');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('SE','SWEDEN');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('SG','SINGAPORE');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('SH','SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('SI','SLOVENIA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('SJ','SVALBARD AND JAN MAYEN');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('SK','SLOVAKIA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('SL','SIERRA LEONE');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('SM','SAN MARINO');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('SN','SENEGAL');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('SO','SOMALIA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('SR','SURINAME');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('SS','SOUTH SUDAN');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('ST','SAO TOME AND PRINCIPE');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('SV','EL SALVADOR');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('SX','SINT MAARTEN (DUTCH PART)');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('SY','SYRIAN ARAB REPUBLIC');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('SZ','SWAZILAND');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('TC','TURKS AND CAICOS ISLANDS');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('TD','CHAD');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('TF','FRENCH SOUTHERN TERRITORIES');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('TG','TOGO');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('TH','THAILAND');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('TJ','TAJIKISTAN');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('TK','TOKELAU');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('TL','TIMOR-LESTE');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('TM','TURKMENISTAN');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('TN','TUNISIA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('TO','TONGA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('TR','TURKEY');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('TT','TRINIDAD AND TOBAGO');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('TV','TUVALU');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('TW','TAIWAN, PROVINCE OF CHINA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('TZ','TANZANIA, UNITED REPUBLIC OF');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('UA','UKRAINE');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('UG','UGANDA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('UM','UNITED STATES MINOR OUTLYING ISLANDS');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('US','UNITED STATES');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('UY','URUGUAY');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('UZ','UZBEKISTAN');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('VA','HOLY SEE (VATICAN CITY STATE)');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('VC','SAINT VINCENT AND THE GRENADINES');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('VE','VENEZUELA, BOLIVARIAN REPUBLIC OF');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('VG','VIRGIN ISLANDS, BRITISH');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('VI','VIRGIN ISLANDS, U.S.');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('VN','VIET NAM');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('VU','VANUATU');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('WF','WALLIS AND FUTUNA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('WS','SAMOA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('YE','YEMEN');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('YT','MAYOTTE');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('ZA','SOUTH AFRICA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('ZM','ZAMBIA');
insert into `buneli_country`(`cod_country`,`txt_country`) values ('ZW','ZIMBABWE');
